parameters:
    migrationOutputDirectory: ""

services:
    migrationGenerator:
        class: Silktide\Reposition\Phinx\MigrationGenerator
        arguments:
            - "@silktide_reposition.metadataProvider"
            - "%migrationOutputDirectory%"

    generateMigrations.command:
        class: Silktide\Reposition\Phinx\GenerateMigrationsCommand
        arguments:
            - "@migrationGenerator"
