parameters:
    migrationOutputDirectory: ""
    configurationOutputDirectory: ""
    
    dbDriver: "%lexide_reposition-sql.dbDriver%"
    dbHost: "%lexide_reposition-sql.dbHost%"
    dbName: "%lexide_reposition-sql.dbName%"
    dbUsername: "%lexide_reposition-sql.dbUsername%"
    dbPassword: "%lexide_reposition-sql.dbPassword%"

services:
    migrationGenerator:
        class: Lexide\Reposition\Phinx\MigrationGenerator
        arguments:
            - "@lexide_reposition.metadataProvider"
            - "%migrationOutputDirectory%"

    generateMigrations.command:
        class: Lexide\Reposition\Phinx\GenerateMigrationsCommand
        arguments:
            - "@migrationGenerator"
        tags:
            - "console.command"

    initialisePhinx.command:
        class: Lexide\Reposition\Phinx\InitialisePhinxCommand
        arguments:
            - "%configurationOutputDirectory%"
            - "%migrationOutputDirectory%"
            - "%dbDriver%"
            - "%dbHost%"
            - "%dbName%"
            - "%dbUsername%"
            - "%dbPassword%"
        tags:
            - "console.command"
